-- StewardHQ V1.1
-- Live auth, auditability, integration registry and execution run ledger.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned_role text;
begin
  -- V1 rule: the first authenticated profile is the owner. Every later account
  -- is created as staff and has no RLS access until explicit staff policies are added.
  if exists(select 1 from public.profiles where role = 'owner') then
    assigned_role := 'staff';
  else
    assigned_role := 'owner';
  end if;

  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    assigned_role
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Make updated_at reliable on the tables that use it.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['profiles','businesses','projects','agents','tasks','memory']
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute procedure public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end $$;

-- Owners may write audit records generated by authenticated server actions.
drop policy if exists "owner_audit_insert" on public.audit_log;
create policy "owner_audit_insert"
on public.audit_log
for insert
with check (public.is_owner());

-- Provider/integration registry. Secrets stay in environment variables or a
-- dedicated secret store; this table only tracks operational state and metadata.
create table if not exists public.integrations (
  id uuid primary key default gen_random_uuid(),
  provider text not null unique,
  display_name text not null,
  status text not null default 'not_configured',
  endpoint_hint text,
  metadata jsonb not null default '{}'::jsonb,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.integrations enable row level security;
drop policy if exists "owner_integrations" on public.integrations;
create policy "owner_integrations"
on public.integrations
for all
using (public.is_owner())
with check (public.is_owner());

drop trigger if exists set_integrations_updated_at on public.integrations;
create trigger set_integrations_updated_at
before update on public.integrations
for each row execute procedure public.set_updated_at();

-- One record per attempt to dispatch work to an AI/human worker.
create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  task_id uuid references public.tasks(id) on delete set null,
  agent_id uuid references public.agents(id) on delete set null,
  provider text not null,
  external_run_id text,
  status text not null default 'queued',
  input_summary text,
  output_summary text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.agent_runs enable row level security;
drop policy if exists "owner_agent_runs" on public.agent_runs;
create policy "owner_agent_runs"
on public.agent_runs
for all
using (public.is_owner())
with check (public.is_owner());

create index if not exists tasks_business_status_idx on public.tasks(business_id, status);
create index if not exists approvals_business_status_idx on public.approvals(business_id, status);
create index if not exists agent_runs_task_idx on public.agent_runs(task_id);
create index if not exists memory_business_category_idx on public.memory(business_id, category);

insert into public.integrations (provider, display_name, status) values
('supabase','Supabase','configured'),
('openai','OpenAI','not_configured'),
('anthropic','Anthropic / Claude','not_configured'),
('accio','Accio Work','not_configured')
on conflict (provider) do nothing;
